<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Optimizer</label>
    <navType>Console</navType>
    <tabs>standard-OrgMetric</tabs>
    <tabs>New_Object_Test__c</tabs>
    <tabs>Test_Obj__c</tabs>
    <tabs>NewObjMar28__c</tabs>
    <tabs>HDT_MM__c</tabs>
    <tabs>M29_Object_Test__c</tabs>
    <tabs>Obj__c</tabs>
    <tabs>Ampol_Aust__c</tabs>
    <tabs>New_Objects__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>Ampol_Aust__c</tab>
        </mappings>
        <mappings>
            <tab>HDT_MM__c</tab>
        </mappings>
        <mappings>
            <tab>M29_Object_Test__c</tab>
        </mappings>
        <mappings>
            <tab>NewObjMar28__c</tab>
        </mappings>
        <mappings>
            <tab>New_Object_Test__c</tab>
        </mappings>
        <mappings>
            <tab>New_Objects__c</tab>
        </mappings>
        <mappings>
            <tab>Obj__c</tab>
        </mappings>
        <mappings>
            <tab>Test_Obj__c</tab>
        </mappings>
        <mappings>
            <tab>standard-OrgMetric</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
