<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Optimizer</label>
    <navType>Console</navType>
    <tabs>standard-OrgMetric</tabs>
    <tabs>New_Object_Test__c</tabs>
    <tabs>Test_Obj__c</tabs>
    <tabs>NewObjMar28__c</tabs>
    <tabs>HDT_MM__c</tabs>
    <tabs>M29_Object_Test__c</tabs>
    <tabs>Obj__c</tabs>
    <tabs>New_Objects__c</tabs>
    <tabs>Object_Work__c</tabs>
    <tabs>TestObjectA21__c</tabs>
    <tabs>Todays_Obj__c</tabs>
    <tabs>New_Object_M23__c</tabs>
    <tabs>KPMG_Change__c</tabs>
    <tabs>VersionObject25__c</tabs>
    <tabs>ObjsDemos__c</tabs>
    <tabs>NObj__c</tabs>
    <tabs>Rand_Stan_Obj__c</tabs>
    <tabs>DrTnSW__c</tabs>
    <tabs>CustObj__c</tabs>
    <tabs>Audinate_Object__c</tabs>
    <tabs>StaTsArk__c</tabs>
    <tabs>NewObjectC__c</tabs>
    <tabs>ObjectTC__c</tabs>
    <tabs>TestObject__c</tabs>
    <tabs>KSCustObj__c</tabs>
    <tabs>Test_Change__c</tabs>
    <tabs>TrailBlazer__c</tabs>
    <tabs>New_OSBObj__c</tabs>
    <tabs>Sept8Obj__c</tabs>
    <tabs>Field_Integrity_Check__c</tabs>
    <tabs>New_Object__c</tabs>
    <tabs>Object_New_OLS__c</tabs>
    <tabs>Tobjsept14__c</tabs>
    <tabs>NObjs__c</tabs>
    <tabs>New_Obj_OCt11__c</tabs>
    <tabs>Favorite__c</tabs>
    <tabs>TestObj__c</tabs>
    <tabs>FavProp__c</tabs>
    <tabs>NObject_Demo__c</tabs>
    <tabs>ObjectCI__c</tabs>
    <tabs>NObjDec27__c</tabs>
    <tabs>BTObjs__c</tabs>
    <tabs>NTestObject__c</tabs>
    <tabs>TestNewObjectCreation__c</tabs>
    <tabs>NObjectsTas__c</tabs>
    <tabs>TObj__c</tabs>
    <tabs>eServe_Obj__c</tabs>
    <tabs>NOCian__c</tabs>
    <tabs>TstObjAR__c</tabs>
    <tabs>SASm__c</tabs>
    <tabs>NObje__c</tabs>
    <tabs>NObjaQT__c</tabs>
    <tabs>TObjs__c</tabs>
    <tabs>NTObjects__c</tabs>
    <tabs>TNOsb__c</tabs>
    <tabs>TDOS__c</tabs>
    <tabs>NObjectCH__c</tabs>
    <tabs>ABTest__c</tabs>
    <tabs>TestRO__c</tabs>
    <tabs>NTObject__c</tabs>
    <tabs>CObj__c</tabs>
    <tabs>NCObj__c</tabs>
    <tabs>May8SP__c</tabs>
    <tabs>TestObjM11__c</tabs>
    <tabs>STOJs__c</tabs>
    <tabs>TObjectSS__c</tabs>
    <tabs>NewCustObject__c</tabs>
    <tabs>Test_Obj_NC__c</tabs>
    <tabs>TCJ198__c</tabs>
    <tabs>SVT_OD__c</tabs>
    <tabs>PropO__c</tabs>
    <tabs>TestDemoNewChange__c</tabs>
    <tabs>NObjVT__c</tabs>
    <tabs>JOH3__c</tabs>
    <tabs>LIDemoObj__c</tabs>
    <tabs>OTCJet__c</tabs>
    <tabs>Cobj1__c</tabs>
    <tabs>TYRO__c</tabs>
    <tabs>OPAPs__c</tabs>
    <tabs>TTDLs__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>ABTest__c</tab>
        </mappings>
        <mappings>
            <tab>Audinate_Object__c</tab>
        </mappings>
        <mappings>
            <tab>BTObjs__c</tab>
        </mappings>
        <mappings>
            <tab>CObj__c</tab>
        </mappings>
        <mappings>
            <tab>Cobj1__c</tab>
        </mappings>
        <mappings>
            <tab>CustObj__c</tab>
        </mappings>
        <mappings>
            <tab>DrTnSW__c</tab>
        </mappings>
        <mappings>
            <tab>FavProp__c</tab>
        </mappings>
        <mappings>
            <tab>Favorite__c</tab>
        </mappings>
        <mappings>
            <tab>Field_Integrity_Check__c</tab>
        </mappings>
        <mappings>
            <tab>HDT_MM__c</tab>
        </mappings>
        <mappings>
            <tab>JOH3__c</tab>
        </mappings>
        <mappings>
            <tab>KPMG_Change__c</tab>
        </mappings>
        <mappings>
            <tab>KSCustObj__c</tab>
        </mappings>
        <mappings>
            <tab>LIDemoObj__c</tab>
        </mappings>
        <mappings>
            <tab>M29_Object_Test__c</tab>
        </mappings>
        <mappings>
            <tab>May8SP__c</tab>
        </mappings>
        <mappings>
            <tab>NCObj__c</tab>
        </mappings>
        <mappings>
            <tab>NOCian__c</tab>
        </mappings>
        <mappings>
            <tab>NObjDec27__c</tab>
        </mappings>
        <mappings>
            <tab>NObjVT__c</tab>
        </mappings>
        <mappings>
            <tab>NObj__c</tab>
        </mappings>
        <mappings>
            <tab>NObjaQT__c</tab>
        </mappings>
        <mappings>
            <tab>NObje__c</tab>
        </mappings>
        <mappings>
            <tab>NObjectCH__c</tab>
        </mappings>
        <mappings>
            <tab>NObject_Demo__c</tab>
        </mappings>
        <mappings>
            <tab>NObjectsTas__c</tab>
        </mappings>
        <mappings>
            <tab>NObjs__c</tab>
        </mappings>
        <mappings>
            <tab>NTObject__c</tab>
        </mappings>
        <mappings>
            <tab>NTObjects__c</tab>
        </mappings>
        <mappings>
            <tab>NTestObject__c</tab>
        </mappings>
        <mappings>
            <tab>NewCustObject__c</tab>
        </mappings>
        <mappings>
            <tab>NewObjMar28__c</tab>
        </mappings>
        <mappings>
            <tab>NewObjectC__c</tab>
        </mappings>
        <mappings>
            <tab>New_OSBObj__c</tab>
        </mappings>
        <mappings>
            <tab>New_Obj_OCt11__c</tab>
        </mappings>
        <mappings>
            <tab>New_Object_M23__c</tab>
        </mappings>
        <mappings>
            <tab>New_Object_Test__c</tab>
        </mappings>
        <mappings>
            <tab>New_Object__c</tab>
        </mappings>
        <mappings>
            <tab>New_Objects__c</tab>
        </mappings>
        <mappings>
            <tab>OPAPs__c</tab>
        </mappings>
        <mappings>
            <tab>OTCJet__c</tab>
        </mappings>
        <mappings>
            <tab>Obj__c</tab>
        </mappings>
        <mappings>
            <tab>ObjectCI__c</tab>
        </mappings>
        <mappings>
            <tab>ObjectTC__c</tab>
        </mappings>
        <mappings>
            <tab>Object_New_OLS__c</tab>
        </mappings>
        <mappings>
            <tab>Object_Work__c</tab>
        </mappings>
        <mappings>
            <tab>ObjsDemos__c</tab>
        </mappings>
        <mappings>
            <tab>PropO__c</tab>
        </mappings>
        <mappings>
            <tab>Rand_Stan_Obj__c</tab>
        </mappings>
        <mappings>
            <tab>SASm__c</tab>
        </mappings>
        <mappings>
            <tab>STOJs__c</tab>
        </mappings>
        <mappings>
            <tab>SVT_OD__c</tab>
        </mappings>
        <mappings>
            <tab>Sept8Obj__c</tab>
        </mappings>
        <mappings>
            <tab>StaTsArk__c</tab>
        </mappings>
        <mappings>
            <tab>TCJ198__c</tab>
        </mappings>
        <mappings>
            <tab>TDOS__c</tab>
        </mappings>
        <mappings>
            <tab>TNOsb__c</tab>
        </mappings>
        <mappings>
            <tab>TObj__c</tab>
        </mappings>
        <mappings>
            <tab>TObjectSS__c</tab>
        </mappings>
        <mappings>
            <tab>TObjs__c</tab>
        </mappings>
        <mappings>
            <tab>TTDLs__c</tab>
        </mappings>
        <mappings>
            <tab>TYRO__c</tab>
        </mappings>
        <mappings>
            <tab>TestDemoNewChange__c</tab>
        </mappings>
        <mappings>
            <tab>TestNewObjectCreation__c</tab>
        </mappings>
        <mappings>
            <tab>TestObjM11__c</tab>
        </mappings>
        <mappings>
            <tab>TestObj__c</tab>
        </mappings>
        <mappings>
            <tab>TestObjectA21__c</tab>
        </mappings>
        <mappings>
            <tab>TestObject__c</tab>
        </mappings>
        <mappings>
            <tab>TestRO__c</tab>
        </mappings>
        <mappings>
            <tab>Test_Change__c</tab>
        </mappings>
        <mappings>
            <tab>Test_Obj_NC__c</tab>
        </mappings>
        <mappings>
            <tab>Test_Obj__c</tab>
        </mappings>
        <mappings>
            <tab>Tobjsept14__c</tab>
        </mappings>
        <mappings>
            <tab>Todays_Obj__c</tab>
        </mappings>
        <mappings>
            <tab>TrailBlazer__c</tab>
        </mappings>
        <mappings>
            <tab>TstObjAR__c</tab>
        </mappings>
        <mappings>
            <tab>VersionObject25__c</tab>
        </mappings>
        <mappings>
            <tab>eServe_Obj__c</tab>
        </mappings>
        <mappings>
            <tab>standard-OrgMetric</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
