<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Approvals</label>
    <navType>Console</navType>
    <tabs>standard-ApprovalsHome</tabs>
    <tabs>Cobj1__c</tabs>
    <tabs>TYRO__c</tabs>
    <tabs>OPAPs__c</tabs>
    <tabs>TTDLs__c</tabs>
    <uiType>Lightning</uiType>
    <workspaceConfig>
        <mappings>
            <tab>Cobj1__c</tab>
        </mappings>
        <mappings>
            <tab>OPAPs__c</tab>
        </mappings>
        <mappings>
            <tab>TTDLs__c</tab>
        </mappings>
        <mappings>
            <tab>TYRO__c</tab>
        </mappings>
        <mappings>
            <tab>standard-ApprovalsHome</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
