<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <tabs>standard-UserProfile</tabs>
    <tabs>standard-Chatter</tabs>
    <tabs>standard-OtherUserProfile</tabs>
    <tabs>New_Object_Test__c</tabs>
    <tabs>Test_Obj__c</tabs>
    <tabs>NewObjMar28__c</tabs>
    <tabs>HDT_MM__c</tabs>
    <tabs>M29_Object_Test__c</tabs>
    <tabs>Obj__c</tabs>
    <tabs>Ampol_Aust__c</tabs>
    <tabs>New_Objects__c</tabs>
    <tabs>A13_Object__c</tabs>
    <tabs>Object_Work__c</tabs>
    <tabs>TestObjectA21__c</tabs>
    <tabs>Todays_Obj__c</tabs>
    <tabs>CheckTest__c</tabs>
    <tabs>New_Object_M23__c</tabs>
    <tabs>KPMG_Change__c</tabs>
    <tabs>VersionObject25__c</tabs>
    <tabs>ObjsDemos__c</tabs>
    <tabs>Testags__c</tabs>
    <tabs>NObj__c</tabs>
    <tabs>Rand_Stan_Obj__c</tabs>
    <tabs>DrTnSW__c</tabs>
    <tabs>CustObj__c</tabs>
    <tabs>Audinate_Object__c</tabs>
    <tabs>StaTsArk__c</tabs>
    <tabs>NewObjectC__c</tabs>
    <tabs>ObjectTC__c</tabs>
    <tabs>TestObject__c</tabs>
    <tabs>KSCustObj__c</tabs>
    <tabs>Test_Change__c</tabs>
    <tabs>TrailBlazer__c</tabs>
    <tabs>New_OSBObj__c</tabs>
    <tabs>Sept8Obj__c</tabs>
    <tabs>NAudi10__c</tabs>
    <tabs>Field_Integrity_Check__c</tabs>
    <tabs>New_Object__c</tabs>
    <tabs>Tobjsept14__c</tabs>
    <tabs>NObjs__c</tabs>
    <tabs>New_Obj_OCt11__c</tabs>
    <tabs>Favorite__c</tabs>
    <tabs>TestObj__c</tabs>
    <tabs>FavProp__c</tabs>
    <tabs>NObject_Demo__c</tabs>
    <tabs>ObjectCI__c</tabs>
    <tabs>BerkshireObject__c</tabs>
    <tabs>NObjDec27__c</tabs>
    <tabs>BTObjs__c</tabs>
    <tabs>NTestObject__c</tabs>
    <tabs>TestNewObjectCreation__c</tabs>
    <tabs>NObjectsTas__c</tabs>
    <tabs>TObj__c</tabs>
    <tabs>eServe_Obj__c</tabs>
    <tabs>NOCian__c</tabs>
    <tabs>TstObjAR__c</tabs>
</CustomApplication>
