<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <consoleConfig>
        <detailPageRefreshMethod>none</detailPageRefreshMethod>
        <keyboardShortcuts>
            <defaultShortcuts>
                <action>FOCUS_CONSOLE</action>
                <active>true</active>
                <keyCommand>ESC</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_NAVIGATOR_TAB</action>
                <active>true</active>
                <keyCommand>V</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_DETAIL_VIEW</action>
                <active>true</active>
                <keyCommand>SHIFT+S</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_PRIMARY_TAB_PANEL</action>
                <active>true</active>
                <keyCommand>P</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_SUBTAB_PANEL</action>
                <active>true</active>
                <keyCommand>S</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_LIST_VIEW</action>
                <active>true</active>
                <keyCommand>N</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_FIRST_LIST_VIEW</action>
                <active>true</active>
                <keyCommand>SHIFT+F</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_SEARCH_INPUT</action>
                <active>true</active>
                <keyCommand>R</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>MOVE_LEFT</action>
                <active>true</active>
                <keyCommand>LEFT ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>MOVE_RIGHT</action>
                <active>true</active>
                <keyCommand>RIGHT ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>UP_ARROW</action>
                <active>true</active>
                <keyCommand>UP ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>DOWN_ARROW</action>
                <active>true</active>
                <keyCommand>DOWN ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>OPEN_TAB_SCROLLER_MENU</action>
                <active>true</active>
                <keyCommand>D</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>OPEN_TAB</action>
                <active>true</active>
                <keyCommand>T</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>CLOSE_TAB</action>
                <active>true</active>
                <keyCommand>C</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>REFRESH_TAB</action>
                <active>false</active>
                <keyCommand>SHIFT+R</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>ENTER</action>
                <active>true</active>
                <keyCommand>ENTER</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>EDIT</action>
                <active>true</active>
                <keyCommand>E</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>SAVE</action>
                <active>true</active>
                <keyCommand>CTRL+S</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>CONSOLE_LINK_DIALOG</action>
                <active>false</active>
                <keyCommand>U</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>HOTKEYS_PANEL</action>
                <active>false</active>
                <keyCommand>SHIFT+K</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_MACRO</action>
                <active>false</active>
                <keyCommand>M</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>FOCUS_FOOTER_PANEL</action>
                <active>false</active>
                <keyCommand>F</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_LIST_VIEW</action>
                <active>false</active>
                <keyCommand>SHIFT+N</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_LEFT_SIDEBAR</action>
                <active>false</active>
                <keyCommand>SHIFT+LEFT ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_RIGHT_SIDEBAR</action>
                <active>false</active>
                <keyCommand>SHIFT+RIGHT ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_TOP_SIDEBAR</action>
                <active>false</active>
                <keyCommand>SHIFT+UP ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_BOTTOM_SIDEBAR</action>
                <active>false</active>
                <keyCommand>SHIFT+DOWN ARROW</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>TOGGLE_APP_LEVEL_COMPONENTS</action>
                <active>false</active>
                <keyCommand>Z</keyCommand>
            </defaultShortcuts>
            <defaultShortcuts>
                <action>REOPEN_LAST_TAB</action>
                <active>false</active>
                <keyCommand>SHIFT+C</keyCommand>
            </defaultShortcuts>
        </keyboardShortcuts>
        <listPlacement>
            <location>full</location>
        </listPlacement>
        <listRefreshMethod>none</listRefreshMethod>
    </consoleConfig>
    <defaultLandingTab>standard-home</defaultLandingTab>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isServiceCloudConsole>true</isServiceCloudConsole>
    <preferences>
        <enableCustomizeMyTabs>false</enableCustomizeMyTabs>
        <enableKeyboardShortcuts>true</enableKeyboardShortcuts>
        <enableListViewHover>true</enableListViewHover>
        <enableListViewReskin>true</enableListViewReskin>
        <enableMultiMonitorComponents>true</enableMultiMonitorComponents>
        <enablePinTabs>true</enablePinTabs>
        <enableTabHover>false</enableTabHover>
        <enableTabLimits>false</enableTabLimits>
        <saveUserSessions>true</saveUserSessions>
    </preferences>
    <tabs>standard-Account</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Case</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>standard-Lead</tabs>
    <tabs>standard-Knowledge</tabs>
    <tabs>HCare__c</tabs>
    <tabs>ACC__c</tabs>
    <tabs>ThinkTank__c</tabs>
    <tabs>AIAco__c</tabs>
    <tabs>ACT__c</tabs>
    <tabs>Mock_Demo__c</tabs>
    <tabs>MarObject__c</tabs>
    <tabs>SeekObj__c</tabs>
    <tabs>BarcoObj__c</tabs>
    <tabs>MetaObject__c</tabs>
    <tabs>IBMObject__c</tabs>
    <tabs>WBP_Obj__c</tabs>
    <tabs>TDB__c</tabs>
    <tabs>CK_test_obj__c</tabs>
    <tabs>PwC__c</tabs>
    <tabs>CitiOb__c</tabs>
    <tabs>BofA_Obj__c</tabs>
    <tabs>ObjMass__c</tabs>
    <tabs>CKDemo__c</tabs>
    <tabs>teobjs19__c</tabs>
    <tabs>Demo_Obj__c</tabs>
    <tabs>TestObjectSW__c</tabs>
    <tabs>TestObjAug__c</tabs>
    <tabs>HD_Obj__c</tabs>
    <tabs>SObj_Demo__c</tabs>
    <tabs>FBObject__c</tabs>
    <tabs>RegObj__c</tabs>
    <workspaceConfig>
        <mappings>
            <tab>ACC__c</tab>
        </mappings>
        <mappings>
            <tab>ACT__c</tab>
        </mappings>
        <mappings>
            <tab>AIAco__c</tab>
        </mappings>
        <mappings>
            <tab>BarcoObj__c</tab>
        </mappings>
        <mappings>
            <tab>BofA_Obj__c</tab>
        </mappings>
        <mappings>
            <tab>CKDemo__c</tab>
        </mappings>
        <mappings>
            <tab>CK_test_obj__c</tab>
        </mappings>
        <mappings>
            <tab>CitiOb__c</tab>
        </mappings>
        <mappings>
            <tab>Demo_Obj__c</tab>
        </mappings>
        <mappings>
            <tab>FBObject__c</tab>
        </mappings>
        <mappings>
            <tab>HCare__c</tab>
        </mappings>
        <mappings>
            <tab>HD_Obj__c</tab>
        </mappings>
        <mappings>
            <tab>IBMObject__c</tab>
        </mappings>
        <mappings>
            <tab>MarObject__c</tab>
        </mappings>
        <mappings>
            <tab>MetaObject__c</tab>
        </mappings>
        <mappings>
            <tab>Mock_Demo__c</tab>
        </mappings>
        <mappings>
            <tab>ObjMass__c</tab>
        </mappings>
        <mappings>
            <tab>PwC__c</tab>
        </mappings>
        <mappings>
            <tab>RegObj__c</tab>
        </mappings>
        <mappings>
            <tab>SObj_Demo__c</tab>
        </mappings>
        <mappings>
            <tab>SeekObj__c</tab>
        </mappings>
        <mappings>
            <tab>TDB__c</tab>
        </mappings>
        <mappings>
            <tab>TestObjAug__c</tab>
        </mappings>
        <mappings>
            <tab>TestObjectSW__c</tab>
        </mappings>
        <mappings>
            <tab>ThinkTank__c</tab>
        </mappings>
        <mappings>
            <tab>WBP_Obj__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Account</tab>
        </mappings>
        <mappings>
            <fieldName>AccountId</fieldName>
            <tab>standard-Case</tab>
        </mappings>
        <mappings>
            <fieldName>AccountId</fieldName>
            <tab>standard-Contact</tab>
        </mappings>
        <mappings>
            <tab>standard-Knowledge</tab>
        </mappings>
        <mappings>
            <tab>standard-Lead</tab>
        </mappings>
        <mappings>
            <fieldName>AccountId</fieldName>
            <tab>standard-Opportunity</tab>
        </mappings>
        <mappings>
            <tab>teobjs19__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
