<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <tabs>standard-Chatter</tabs>
    <tabs>standard-Campaign</tabs>
    <tabs>standard-Lead</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>standard-Forecasting3</tabs>
    <tabs>standard-Contract</tabs>
    <tabs>standard-Order</tabs>
    <tabs>standard-Invoice</tabs>
    <tabs>standard-Case</tabs>
    <tabs>standard-Solution</tabs>
    <tabs>standard-Product2</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>BNZ__c</tabs>
    <tabs>Sept_29_MyObj__c</tabs>
    <tabs>Test_Object_Oct4__c</tabs>
    <tabs>Sprint1Rel1__c</tabs>
    <tabs>Test_Nov_11_Object__c</tabs>
    <tabs>NewProp__c</tabs>
    <tabs>TN11_28S__c</tabs>
    <tabs>TestN20__c</tabs>
    <tabs>CObject_Feb_16__c</tabs>
    <tabs>New_Object_Test__c</tabs>
    <tabs>Test_Obj__c</tabs>
    <tabs>NewObjMar28__c</tabs>
    <tabs>HDT_MM__c</tabs>
    <tabs>M29_Object_Test__c</tabs>
    <tabs>Obj__c</tabs>
    <tabs>New_Objects__c</tabs>
    <tabs>Object_Work__c</tabs>
    <tabs>TestObjectA21__c</tabs>
    <tabs>Todays_Obj__c</tabs>
    <tabs>New_Object_M23__c</tabs>
    <tabs>KPMG_Change__c</tabs>
    <tabs>VersionObject25__c</tabs>
    <tabs>ObjsDemos__c</tabs>
    <tabs>NObj__c</tabs>
    <tabs>Rand_Stan_Obj__c</tabs>
    <tabs>DrTnSW__c</tabs>
    <tabs>CustObj__c</tabs>
    <tabs>Audinate_Object__c</tabs>
    <tabs>StaTsArk__c</tabs>
    <tabs>NewObjectC__c</tabs>
    <tabs>ObjectTC__c</tabs>
    <tabs>TestObject__c</tabs>
    <tabs>KSCustObj__c</tabs>
    <tabs>Test_Change__c</tabs>
    <tabs>TrailBlazer__c</tabs>
    <tabs>New_OSBObj__c</tabs>
    <tabs>Sept8Obj__c</tabs>
    <tabs>Field_Integrity_Check__c</tabs>
    <tabs>New_Object__c</tabs>
    <tabs>Object_New_OLS__c</tabs>
    <tabs>Tobjsept14__c</tabs>
    <tabs>NObjs__c</tabs>
    <tabs>New_Obj_OCt11__c</tabs>
    <tabs>Favorite__c</tabs>
    <tabs>TestObj__c</tabs>
    <tabs>FavProp__c</tabs>
    <tabs>NObject_Demo__c</tabs>
    <tabs>ObjectCI__c</tabs>
    <tabs>NObjDec27__c</tabs>
    <tabs>BTObjs__c</tabs>
    <tabs>NTestObject__c</tabs>
    <tabs>TestNewObjectCreation__c</tabs>
    <tabs>NObjectsTas__c</tabs>
    <tabs>TObj__c</tabs>
    <tabs>eServe_Obj__c</tabs>
    <tabs>NOCian__c</tabs>
    <tabs>TstObjAR__c</tabs>
    <tabs>SASm__c</tabs>
    <tabs>NObje__c</tabs>
    <tabs>NObjaQT__c</tabs>
    <tabs>TObjs__c</tabs>
    <tabs>NTObjects__c</tabs>
    <tabs>TNOsb__c</tabs>
    <tabs>TDOS__c</tabs>
    <tabs>NObjectCH__c</tabs>
    <tabs>ABTest__c</tabs>
    <tabs>TestRO__c</tabs>
    <tabs>NTObject__c</tabs>
    <tabs>CObj__c</tabs>
    <tabs>NCObj__c</tabs>
    <tabs>May8SP__c</tabs>
    <tabs>TestObjM11__c</tabs>
    <tabs>STOJs__c</tabs>
    <tabs>TObjectSS__c</tabs>
    <tabs>NewCustObject__c</tabs>
    <tabs>Test_Obj_NC__c</tabs>
    <tabs>TCJ198__c</tabs>
    <tabs>SVT_OD__c</tabs>
    <tabs>PropO__c</tabs>
    <tabs>TestDemoNewChange__c</tabs>
    <tabs>NObjVT__c</tabs>
    <tabs>JOH3__c</tabs>
    <tabs>LIDemoObj__c</tabs>
    <tabs>OTCJet__c</tabs>
    <tabs>Cobj1__c</tabs>
    <tabs>TYRO__c</tabs>
    <tabs>OPAPs__c</tabs>
    <tabs>TTDLs__c</tabs>
</CustomApplication>
