<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <classAccesses>
        <apexClass>AccountService</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>BotField</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CaseService</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>TooManyMethods</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <custom>false</custom>
    <fieldPermissions>
        <editable>true</editable>
        <field>Course__c.Subject__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>DBUS__c.DBField__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>MTX_Cust_Obj__c.Emp_Start_Date__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>SNCFobj__c.CC109__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>Sensei__c.Classes__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>YTurquoise__c.PickList_Value__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <layoutAssignments>
        <layout>MTX_Cust_Obj__c-MTX_Cust_Obj Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>SNCFobj__c-SNCFobj Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Sensei__c-Sensei Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>YTurquoise__c-YTurquoise Layout</layout>
    </layoutAssignments>
    <tabVisibilities>
        <tab>MTX_Cust_Obj__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>SNCFobj__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Sensei__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <userLicense>Einstein Agent</userLicense>
    <userPermissions>
        <enabled>true</enabled>
        <name>ApiEnabled</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ApiUserOnly</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>DigitalAgentUser</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>RunFlow</name>
    </userPermissions>
</Profile>