<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <classAccesses>
        <apexClass>AccountService</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AccountServiceTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>BotMessageButton</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>CaseService</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>ContactService</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>DynamicFieldUpdater</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>DynamicFieldUpdaterTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>DynamicRecordService</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>DynamicRecordServiceTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <custom>false</custom>
    <externalDataSourceAccesses>
        <enabled>false</enabled>
        <externalDataSource>Vault_Ext_DS_Connect</externalDataSource>
    </externalDataSourceAccesses>
    <fieldPermissions>
        <editable>false</editable>
        <field>Account.AutorabitExtId__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>Delivery__c.Delivery_Email__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>Demo_WIP__c.Demo_WIP_Field__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>MMCustObj__c.MMField__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>MTX_Cust_Obj__c.Emp_Start_Date__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>NameConcat__c.Email__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>false</editable>
        <field>Opportunity.AutorabitExtId__c</field>
        <readable>false</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>SNCFobj__c.CC109__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>TMObj__c.TMField__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <fieldPermissions>
        <editable>true</editable>
        <field>X2026_Custom_Obj__c.SDate__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <flowAccesses>
        <enabled>false</enabled>
        <flow>Add_Case_Comment_V3</flow>
    </flowAccesses>
    <flowAccesses>
        <enabled>false</enabled>
        <flow>Opp_Record_Flow</flow>
    </flowAccesses>
    <flowAccesses>
        <enabled>false</enabled>
        <flow>Opp_Updates</flow>
    </flowAccesses>
    <layoutAssignments>
        <layout>AObject_Tas__c-AObject-Tas Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>AutoNumber__c-AutoNumber Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Delivery__c-Delivery Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Demo_WIP__c-Demo_WIP Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>MMCustObj__c-MMCustObj Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>MTX_Cust_Obj__c-MTX_Cust_Obj Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>NameConcat__c-NameConcat Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>PipeRun__c-PipeRun Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>SNCFobj__c-SNCFobj Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>TMObj__c-TMObj Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>TObjectM12__c-TObjectM12 Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>TestBCA__c-TestBCA Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>X2026_Custom_Obj__c-2026 Custom Obj Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>object_trial__c-object_trial Layout</layout>
    </layoutAssignments>
    <recordTypeVisibilities>
        <default>true</default>
        <recordType>Account.Business_Account</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <tabVisibilities>
        <tab>AObject_Tas__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>AutoNumber__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Delivery__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>Demo_WIP__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>MMCustObj__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>MTX_Cust_Obj__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>PipeRun__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>SNCFobj__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>TMObj__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>TObjectM12__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>TestBCA__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <userLicense>Einstein Agent</userLicense>
    <userPermissions>
        <enabled>true</enabled>
        <name>ApiEnabled</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ApiUserOnly</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>DigitalAgentUser</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>RunFlow</name>
    </userPermissions>
</Profile>